// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: vectorxlite.proto

package vectorxlite_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VectorXLitePB_CreateCollection_FullMethodName = "/vectorxlite_pb.VectorXLitePB/CreateCollection"
	VectorXLitePB_Insert_FullMethodName           = "/vectorxlite_pb.VectorXLitePB/Insert"
	VectorXLitePB_Search_FullMethodName           = "/vectorxlite_pb.VectorXLitePB/Search"
	VectorXLitePB_ExportSnapshot_FullMethodName   = "/vectorxlite_pb.VectorXLitePB/ExportSnapshot"
	VectorXLitePB_ImportSnapshot_FullMethodName   = "/vectorxlite_pb.VectorXLitePB/ImportSnapshot"
)

// VectorXLitePBClient is the client API for VectorXLitePB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VectorXLitePBClient interface {
	CreateCollection(ctx context.Context, in *CollectionConfigPB, opts ...grpc.CallOption) (*EmptyPB, error)
	Insert(ctx context.Context, in *InsertPointPB, opts ...grpc.CallOption) (*EmptyPB, error)
	Search(ctx context.Context, in *SearchPointPB, opts ...grpc.CallOption) (*SearchResponsePB, error)
	// Snapshot operations for Raft FSM integration
	ExportSnapshot(ctx context.Context, in *ExportSnapshotRequestPB, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunkPB], error)
	ImportSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunkPB, ImportSnapshotResponsePB], error)
}

type vectorXLitePBClient struct {
	cc grpc.ClientConnInterface
}

func NewVectorXLitePBClient(cc grpc.ClientConnInterface) VectorXLitePBClient {
	return &vectorXLitePBClient{cc}
}

func (c *vectorXLitePBClient) CreateCollection(ctx context.Context, in *CollectionConfigPB, opts ...grpc.CallOption) (*EmptyPB, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyPB)
	err := c.cc.Invoke(ctx, VectorXLitePB_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorXLitePBClient) Insert(ctx context.Context, in *InsertPointPB, opts ...grpc.CallOption) (*EmptyPB, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyPB)
	err := c.cc.Invoke(ctx, VectorXLitePB_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorXLitePBClient) Search(ctx context.Context, in *SearchPointPB, opts ...grpc.CallOption) (*SearchResponsePB, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponsePB)
	err := c.cc.Invoke(ctx, VectorXLitePB_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vectorXLitePBClient) ExportSnapshot(ctx context.Context, in *ExportSnapshotRequestPB, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotChunkPB], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VectorXLitePB_ServiceDesc.Streams[0], VectorXLitePB_ExportSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportSnapshotRequestPB, SnapshotChunkPB]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VectorXLitePB_ExportSnapshotClient = grpc.ServerStreamingClient[SnapshotChunkPB]

func (c *vectorXLitePBClient) ImportSnapshot(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SnapshotChunkPB, ImportSnapshotResponsePB], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VectorXLitePB_ServiceDesc.Streams[1], VectorXLitePB_ImportSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SnapshotChunkPB, ImportSnapshotResponsePB]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VectorXLitePB_ImportSnapshotClient = grpc.ClientStreamingClient[SnapshotChunkPB, ImportSnapshotResponsePB]

// VectorXLitePBServer is the server API for VectorXLitePB service.
// All implementations must embed UnimplementedVectorXLitePBServer
// for forward compatibility.
type VectorXLitePBServer interface {
	CreateCollection(context.Context, *CollectionConfigPB) (*EmptyPB, error)
	Insert(context.Context, *InsertPointPB) (*EmptyPB, error)
	Search(context.Context, *SearchPointPB) (*SearchResponsePB, error)
	// Snapshot operations for Raft FSM integration
	ExportSnapshot(*ExportSnapshotRequestPB, grpc.ServerStreamingServer[SnapshotChunkPB]) error
	ImportSnapshot(grpc.ClientStreamingServer[SnapshotChunkPB, ImportSnapshotResponsePB]) error
	mustEmbedUnimplementedVectorXLitePBServer()
}

// UnimplementedVectorXLitePBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVectorXLitePBServer struct{}

func (UnimplementedVectorXLitePBServer) CreateCollection(context.Context, *CollectionConfigPB) (*EmptyPB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedVectorXLitePBServer) Insert(context.Context, *InsertPointPB) (*EmptyPB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedVectorXLitePBServer) Search(context.Context, *SearchPointPB) (*SearchResponsePB, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedVectorXLitePBServer) ExportSnapshot(*ExportSnapshotRequestPB, grpc.ServerStreamingServer[SnapshotChunkPB]) error {
	return status.Errorf(codes.Unimplemented, "method ExportSnapshot not implemented")
}
func (UnimplementedVectorXLitePBServer) ImportSnapshot(grpc.ClientStreamingServer[SnapshotChunkPB, ImportSnapshotResponsePB]) error {
	return status.Errorf(codes.Unimplemented, "method ImportSnapshot not implemented")
}
func (UnimplementedVectorXLitePBServer) mustEmbedUnimplementedVectorXLitePBServer() {}
func (UnimplementedVectorXLitePBServer) testEmbeddedByValue()                       {}

// UnsafeVectorXLitePBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VectorXLitePBServer will
// result in compilation errors.
type UnsafeVectorXLitePBServer interface {
	mustEmbedUnimplementedVectorXLitePBServer()
}

func RegisterVectorXLitePBServer(s grpc.ServiceRegistrar, srv VectorXLitePBServer) {
	// If the following call pancis, it indicates UnimplementedVectorXLitePBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VectorXLitePB_ServiceDesc, srv)
}

func _VectorXLitePB_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectionConfigPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorXLitePBServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorXLitePB_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorXLitePBServer).CreateCollection(ctx, req.(*CollectionConfigPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorXLitePB_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertPointPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorXLitePBServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorXLitePB_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorXLitePBServer).Insert(ctx, req.(*InsertPointPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorXLitePB_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPointPB)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VectorXLitePBServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VectorXLitePB_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VectorXLitePBServer).Search(ctx, req.(*SearchPointPB))
	}
	return interceptor(ctx, in, info, handler)
}

func _VectorXLitePB_ExportSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportSnapshotRequestPB)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VectorXLitePBServer).ExportSnapshot(m, &grpc.GenericServerStream[ExportSnapshotRequestPB, SnapshotChunkPB]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VectorXLitePB_ExportSnapshotServer = grpc.ServerStreamingServer[SnapshotChunkPB]

func _VectorXLitePB_ImportSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VectorXLitePBServer).ImportSnapshot(&grpc.GenericServerStream[SnapshotChunkPB, ImportSnapshotResponsePB]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VectorXLitePB_ImportSnapshotServer = grpc.ClientStreamingServer[SnapshotChunkPB, ImportSnapshotResponsePB]

// VectorXLitePB_ServiceDesc is the grpc.ServiceDesc for VectorXLitePB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VectorXLitePB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vectorxlite_pb.VectorXLitePB",
	HandlerType: (*VectorXLitePBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _VectorXLitePB_CreateCollection_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _VectorXLitePB_Insert_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _VectorXLitePB_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportSnapshot",
			Handler:       _VectorXLitePB_ExportSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportSnapshot",
			Handler:       _VectorXLitePB_ImportSnapshot_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "vectorxlite.proto",
}
