// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: vectorxlite/v1/vectorxlite.proto

package vectorxlite_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of file in the snapshot
type SnapshotFileTypePB int32

const (
	SnapshotFileTypePB_SNAPSHOT_FILE_TYPE_UNKNOWN    SnapshotFileTypePB = 0
	SnapshotFileTypePB_SNAPSHOT_FILE_TYPE_SQLITE_DB  SnapshotFileTypePB = 1
	SnapshotFileTypePB_SNAPSHOT_FILE_TYPE_HNSW_INDEX SnapshotFileTypePB = 2
	SnapshotFileTypePB_SNAPSHOT_FILE_TYPE_WAL        SnapshotFileTypePB = 3
)

// Enum value maps for SnapshotFileTypePB.
var (
	SnapshotFileTypePB_name = map[int32]string{
		0: "SNAPSHOT_FILE_TYPE_UNKNOWN",
		1: "SNAPSHOT_FILE_TYPE_SQLITE_DB",
		2: "SNAPSHOT_FILE_TYPE_HNSW_INDEX",
		3: "SNAPSHOT_FILE_TYPE_WAL",
	}
	SnapshotFileTypePB_value = map[string]int32{
		"SNAPSHOT_FILE_TYPE_UNKNOWN":    0,
		"SNAPSHOT_FILE_TYPE_SQLITE_DB":  1,
		"SNAPSHOT_FILE_TYPE_HNSW_INDEX": 2,
		"SNAPSHOT_FILE_TYPE_WAL":        3,
	}
)

func (x SnapshotFileTypePB) Enum() *SnapshotFileTypePB {
	p := new(SnapshotFileTypePB)
	*p = x
	return p
}

func (x SnapshotFileTypePB) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotFileTypePB) Descriptor() protoreflect.EnumDescriptor {
	return file_vectorxlite_v1_vectorxlite_proto_enumTypes[0].Descriptor()
}

func (SnapshotFileTypePB) Type() protoreflect.EnumType {
	return &file_vectorxlite_v1_vectorxlite_proto_enumTypes[0]
}

func (x SnapshotFileTypePB) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotFileTypePB.Descriptor instead.
func (SnapshotFileTypePB) EnumDescriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{0}
}

type EmptyPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyPB) Reset() {
	*x = EmptyPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyPB) ProtoMessage() {}

func (x *EmptyPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyPB.ProtoReflect.Descriptor instead.
func (*EmptyPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{0}
}

type CollectionConfigPB struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Distance           string                 `protobuf:"bytes,2,opt,name=distance,proto3" json:"distance,omitempty"` // e.g. "Cosine" | "Euclidean" | "Dot"
	VectorDimension    uint32                 `protobuf:"varint,3,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"`
	PayloadTableSchema string                 `protobuf:"bytes,4,opt,name=payload_table_schema,json=payloadTableSchema,proto3" json:"payload_table_schema,omitempty"`
	IndexFilePath      string                 `protobuf:"bytes,5,opt,name=index_file_path,json=indexFilePath,proto3" json:"index_file_path,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CollectionConfigPB) Reset() {
	*x = CollectionConfigPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionConfigPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionConfigPB) ProtoMessage() {}

func (x *CollectionConfigPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionConfigPB.ProtoReflect.Descriptor instead.
func (*CollectionConfigPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionConfigPB) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionConfigPB) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *CollectionConfigPB) GetVectorDimension() uint32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

func (x *CollectionConfigPB) GetPayloadTableSchema() string {
	if x != nil {
		return x.PayloadTableSchema
	}
	return ""
}

func (x *CollectionConfigPB) GetIndexFilePath() string {
	if x != nil {
		return x.IndexFilePath
	}
	return ""
}

type InsertPointPB struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Id                 int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector             []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	PayloadInsertQuery string                 `protobuf:"bytes,4,opt,name=payload_insert_query,json=payloadInsertQuery,proto3" json:"payload_insert_query,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InsertPointPB) Reset() {
	*x = InsertPointPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPointPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPointPB) ProtoMessage() {}

func (x *InsertPointPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPointPB.ProtoReflect.Descriptor instead.
func (*InsertPointPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{2}
}

func (x *InsertPointPB) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *InsertPointPB) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertPointPB) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertPointPB) GetPayloadInsertQuery() string {
	if x != nil {
		return x.PayloadInsertQuery
	}
	return ""
}

type SearchPointPB struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Vector             []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK               uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	PayloadSearchQuery string                 `protobuf:"bytes,4,opt,name=payload_search_query,json=payloadSearchQuery,proto3" json:"payload_search_query,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchPointPB) Reset() {
	*x = SearchPointPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPointPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPointPB) ProtoMessage() {}

func (x *SearchPointPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPointPB.ProtoReflect.Descriptor instead.
func (*SearchPointPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{3}
}

func (x *SearchPointPB) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SearchPointPB) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchPointPB) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchPointPB) GetPayloadSearchQuery() string {
	if x != nil {
		return x.PayloadSearchQuery
	}
	return ""
}

type KeyValuePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePB) Reset() {
	*x = KeyValuePB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePB) ProtoMessage() {}

func (x *KeyValuePB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePB.ProtoReflect.Descriptor instead.
func (*KeyValuePB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{4}
}

func (x *KeyValuePB) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePB) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SearchResultItemPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rowid         int64                  `protobuf:"varint,1,opt,name=rowid,proto3" json:"rowid,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Payload       []*KeyValuePB          `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultItemPB) Reset() {
	*x = SearchResultItemPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultItemPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultItemPB) ProtoMessage() {}

func (x *SearchResultItemPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultItemPB.ProtoReflect.Descriptor instead.
func (*SearchResultItemPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResultItemPB) GetRowid() int64 {
	if x != nil {
		return x.Rowid
	}
	return 0
}

func (x *SearchResultItemPB) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResultItemPB) GetPayload() []*KeyValuePB {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SearchResponsePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultItemPB  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponsePB) Reset() {
	*x = SearchResponsePB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponsePB) ProtoMessage() {}

func (x *SearchResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponsePB.ProtoReflect.Descriptor instead.
func (*SearchResponsePB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponsePB) GetResults() []*SearchResultItemPB {
	if x != nil {
		return x.Results
	}
	return nil
}

type CollectionExistsRequestPB struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CollectionExistsRequestPB) Reset() {
	*x = CollectionExistsRequestPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionExistsRequestPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionExistsRequestPB) ProtoMessage() {}

func (x *CollectionExistsRequestPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionExistsRequestPB.ProtoReflect.Descriptor instead.
func (*CollectionExistsRequestPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{7}
}

func (x *CollectionExistsRequestPB) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

type CollectionExistsResponsePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionExistsResponsePB) Reset() {
	*x = CollectionExistsResponsePB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionExistsResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionExistsResponsePB) ProtoMessage() {}

func (x *CollectionExistsResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionExistsResponsePB.ProtoReflect.Descriptor instead.
func (*CollectionExistsResponsePB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{8}
}

func (x *CollectionExistsResponsePB) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Request to export a snapshot
type ExportSnapshotRequestPB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specify chunk size in bytes (default: 64KB)
	ChunkSize uint32 `protobuf:"varint,1,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	// Optional: include index files in snapshot (default: true)
	IncludeIndexFiles bool `protobuf:"varint,2,opt,name=include_index_files,json=includeIndexFiles,proto3" json:"include_index_files,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExportSnapshotRequestPB) Reset() {
	*x = ExportSnapshotRequestPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSnapshotRequestPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSnapshotRequestPB) ProtoMessage() {}

func (x *ExportSnapshotRequestPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSnapshotRequestPB.ProtoReflect.Descriptor instead.
func (*ExportSnapshotRequestPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{9}
}

func (x *ExportSnapshotRequestPB) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *ExportSnapshotRequestPB) GetIncludeIndexFiles() bool {
	if x != nil {
		return x.IncludeIndexFiles
	}
	return false
}

// A chunk of snapshot data streamed during export/import
type SnapshotChunkPB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metadata about the snapshot (sent in first chunk only)
	Metadata *SnapshotMetadataPB `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// File being transferred
	FileChunk *SnapshotFilePB `protobuf:"bytes,2,opt,name=file_chunk,json=fileChunk,proto3" json:"file_chunk,omitempty"`
	// Sequence number for ordering chunks
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Whether this is the final chunk
	IsFinal       bool `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotChunkPB) Reset() {
	*x = SnapshotChunkPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotChunkPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotChunkPB) ProtoMessage() {}

func (x *SnapshotChunkPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotChunkPB.ProtoReflect.Descriptor instead.
func (*SnapshotChunkPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotChunkPB) GetMetadata() *SnapshotMetadataPB {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SnapshotChunkPB) GetFileChunk() *SnapshotFilePB {
	if x != nil {
		return x.FileChunk
	}
	return nil
}

func (x *SnapshotChunkPB) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *SnapshotChunkPB) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

// Metadata about the entire snapshot
type SnapshotMetadataPB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this snapshot
	SnapshotId string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Timestamp when snapshot was created (Unix millis)
	CreatedAt int64 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Total size of all files in bytes
	TotalSize uint64 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// List of files included in the snapshot
	Files []*SnapshotFileInfoPB `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	// Version for compatibility checking
	Version uint32 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	// Checksum of entire snapshot (SHA-256)
	Checksum      string `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotMetadataPB) Reset() {
	*x = SnapshotMetadataPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadataPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadataPB) ProtoMessage() {}

func (x *SnapshotMetadataPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadataPB.ProtoReflect.Descriptor instead.
func (*SnapshotMetadataPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotMetadataPB) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *SnapshotMetadataPB) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SnapshotMetadataPB) GetTotalSize() uint64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *SnapshotMetadataPB) GetFiles() []*SnapshotFileInfoPB {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *SnapshotMetadataPB) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SnapshotMetadataPB) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// Information about a single file in the snapshot
type SnapshotFileInfoPB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Relative path/name of the file
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Type of file (database, index, etc.)
	FileType SnapshotFileTypePB `protobuf:"varint,2,opt,name=file_type,json=fileType,proto3,enum=vectorxlite_pb.SnapshotFileTypePB" json:"file_type,omitempty"`
	// Size of this file in bytes
	FileSize uint64 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	// Checksum of this file (SHA-256)
	Checksum      string `protobuf:"bytes,4,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFileInfoPB) Reset() {
	*x = SnapshotFileInfoPB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFileInfoPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFileInfoPB) ProtoMessage() {}

func (x *SnapshotFileInfoPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFileInfoPB.ProtoReflect.Descriptor instead.
func (*SnapshotFileInfoPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{12}
}

func (x *SnapshotFileInfoPB) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SnapshotFileInfoPB) GetFileType() SnapshotFileTypePB {
	if x != nil {
		return x.FileType
	}
	return SnapshotFileTypePB_SNAPSHOT_FILE_TYPE_UNKNOWN
}

func (x *SnapshotFileInfoPB) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SnapshotFileInfoPB) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

// A chunk of file data
type SnapshotFilePB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the file this chunk belongs to
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// Offset within the file
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The actual data
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// Whether this is the last chunk for this file
	IsLastChunk   bool `protobuf:"varint,4,opt,name=is_last_chunk,json=isLastChunk,proto3" json:"is_last_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotFilePB) Reset() {
	*x = SnapshotFilePB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFilePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFilePB) ProtoMessage() {}

func (x *SnapshotFilePB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFilePB.ProtoReflect.Descriptor instead.
func (*SnapshotFilePB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{13}
}

func (x *SnapshotFilePB) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SnapshotFilePB) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SnapshotFilePB) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnapshotFilePB) GetIsLastChunk() bool {
	if x != nil {
		return x.IsLastChunk
	}
	return false
}

// Response after importing a snapshot
type ImportSnapshotResponsePB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the import was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if failed
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Snapshot ID that was imported
	SnapshotId string `protobuf:"bytes,3,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Number of bytes restored
	BytesRestored uint64 `protobuf:"varint,4,opt,name=bytes_restored,json=bytesRestored,proto3" json:"bytes_restored,omitempty"`
	// Number of files restored
	FilesRestored uint32 `protobuf:"varint,5,opt,name=files_restored,json=filesRestored,proto3" json:"files_restored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportSnapshotResponsePB) Reset() {
	*x = ImportSnapshotResponsePB{}
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSnapshotResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSnapshotResponsePB) ProtoMessage() {}

func (x *ImportSnapshotResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_v1_vectorxlite_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSnapshotResponsePB.ProtoReflect.Descriptor instead.
func (*ImportSnapshotResponsePB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP(), []int{14}
}

func (x *ImportSnapshotResponsePB) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ImportSnapshotResponsePB) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ImportSnapshotResponsePB) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ImportSnapshotResponsePB) GetBytesRestored() uint64 {
	if x != nil {
		return x.BytesRestored
	}
	return 0
}

func (x *ImportSnapshotResponsePB) GetFilesRestored() uint32 {
	if x != nil {
		return x.FilesRestored
	}
	return 0
}

var File_vectorxlite_v1_vectorxlite_proto protoreflect.FileDescriptor

const file_vectorxlite_v1_vectorxlite_proto_rawDesc = "" +
	"\n" +
	" vectorxlite/v1/vectorxlite.proto\x12\x0evectorxlite_pb\"\t\n" +
	"\aEmptyPB\"\xde\x01\n" +
	"\x12CollectionConfigPB\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\tR\bdistance\x12)\n" +
	"\x10vector_dimension\x18\x03 \x01(\rR\x0fvectorDimension\x120\n" +
	"\x14payload_table_schema\x18\x04 \x01(\tR\x12payloadTableSchema\x12&\n" +
	"\x0findex_file_path\x18\x05 \x01(\tR\rindexFilePath\"\x92\x01\n" +
	"\rInsertPointPB\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x120\n" +
	"\x14payload_insert_query\x18\x04 \x01(\tR\x12payloadInsertQuery\"\x97\x01\n" +
	"\rSearchPointPB\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x120\n" +
	"\x14payload_search_query\x18\x04 \x01(\tR\x12payloadSearchQuery\"4\n" +
	"\n" +
	"KeyValuePB\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"|\n" +
	"\x12SearchResultItemPB\x12\x14\n" +
	"\x05rowid\x18\x01 \x01(\x03R\x05rowid\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x124\n" +
	"\apayload\x18\x03 \x03(\v2\x1a.vectorxlite_pb.KeyValuePBR\apayload\"P\n" +
	"\x10SearchResponsePB\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".vectorxlite_pb.SearchResultItemPBR\aresults\"D\n" +
	"\x19CollectionExistsRequestPB\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\"4\n" +
	"\x1aCollectionExistsResponsePB\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"h\n" +
	"\x17ExportSnapshotRequestPB\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x01 \x01(\rR\tchunkSize\x12.\n" +
	"\x13include_index_files\x18\x02 \x01(\bR\x11includeIndexFiles\"\xc7\x01\n" +
	"\x0fSnapshotChunkPB\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".vectorxlite_pb.SnapshotMetadataPBR\bmetadata\x12=\n" +
	"\n" +
	"file_chunk\x18\x02 \x01(\v2\x1e.vectorxlite_pb.SnapshotFilePBR\tfileChunk\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\"\xe3\x01\n" +
	"\x12SnapshotMetadataPB\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04R\ttotalSize\x128\n" +
	"\x05files\x18\x04 \x03(\v2\".vectorxlite_pb.SnapshotFileInfoPBR\x05files\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\"\xab\x01\n" +
	"\x12SnapshotFileInfoPB\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12?\n" +
	"\tfile_type\x18\x02 \x01(\x0e2\".vectorxlite_pb.SnapshotFileTypePBR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x04R\bfileSize\x12\x1a\n" +
	"\bchecksum\x18\x04 \x01(\tR\bchecksum\"}\n" +
	"\x0eSnapshotFilePB\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\"\n" +
	"\ris_last_chunk\x18\x04 \x01(\bR\visLastChunk\"\xc8\x01\n" +
	"\x18ImportSnapshotResponsePB\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vsnapshot_id\x18\x03 \x01(\tR\n" +
	"snapshotId\x12%\n" +
	"\x0ebytes_restored\x18\x04 \x01(\x04R\rbytesRestored\x12%\n" +
	"\x0efiles_restored\x18\x05 \x01(\rR\rfilesRestored*\x95\x01\n" +
	"\x12SnapshotFileTypePB\x12\x1e\n" +
	"\x1aSNAPSHOT_FILE_TYPE_UNKNOWN\x10\x00\x12 \n" +
	"\x1cSNAPSHOT_FILE_TYPE_SQLITE_DB\x10\x01\x12!\n" +
	"\x1dSNAPSHOT_FILE_TYPE_HNSW_INDEX\x10\x02\x12\x1a\n" +
	"\x16SNAPSHOT_FILE_TYPE_WAL\x10\x032\x95\x04\n" +
	"\rVectorXLitePB\x12O\n" +
	"\x10CreateCollection\x12\".vectorxlite_pb.CollectionConfigPB\x1a\x17.vectorxlite_pb.EmptyPB\x12@\n" +
	"\x06Insert\x12\x1d.vectorxlite_pb.InsertPointPB\x1a\x17.vectorxlite_pb.EmptyPB\x12I\n" +
	"\x06Search\x12\x1d.vectorxlite_pb.SearchPointPB\x1a .vectorxlite_pb.SearchResponsePB\x12i\n" +
	"\x10CollectionExists\x12).vectorxlite_pb.CollectionExistsRequestPB\x1a*.vectorxlite_pb.CollectionExistsResponsePB\x12\\\n" +
	"\x0eExportSnapshot\x12'.vectorxlite_pb.ExportSnapshotRequestPB\x1a\x1f.vectorxlite_pb.SnapshotChunkPB0\x01\x12]\n" +
	"\x0eImportSnapshot\x12\x1f.vectorxlite_pb.SnapshotChunkPB\x1a(.vectorxlite_pb.ImportSnapshotResponsePB(\x01BFZDgithub.com/uttom-akash/vector-xlite/go_grpc_client/pb;vectorxlite_pbb\x06proto3"

var (
	file_vectorxlite_v1_vectorxlite_proto_rawDescOnce sync.Once
	file_vectorxlite_v1_vectorxlite_proto_rawDescData []byte
)

func file_vectorxlite_v1_vectorxlite_proto_rawDescGZIP() []byte {
	file_vectorxlite_v1_vectorxlite_proto_rawDescOnce.Do(func() {
		file_vectorxlite_v1_vectorxlite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vectorxlite_v1_vectorxlite_proto_rawDesc), len(file_vectorxlite_v1_vectorxlite_proto_rawDesc)))
	})
	return file_vectorxlite_v1_vectorxlite_proto_rawDescData
}

var file_vectorxlite_v1_vectorxlite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vectorxlite_v1_vectorxlite_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_vectorxlite_v1_vectorxlite_proto_goTypes = []any{
	(SnapshotFileTypePB)(0),            // 0: vectorxlite_pb.SnapshotFileTypePB
	(*EmptyPB)(nil),                    // 1: vectorxlite_pb.EmptyPB
	(*CollectionConfigPB)(nil),         // 2: vectorxlite_pb.CollectionConfigPB
	(*InsertPointPB)(nil),              // 3: vectorxlite_pb.InsertPointPB
	(*SearchPointPB)(nil),              // 4: vectorxlite_pb.SearchPointPB
	(*KeyValuePB)(nil),                 // 5: vectorxlite_pb.KeyValuePB
	(*SearchResultItemPB)(nil),         // 6: vectorxlite_pb.SearchResultItemPB
	(*SearchResponsePB)(nil),           // 7: vectorxlite_pb.SearchResponsePB
	(*CollectionExistsRequestPB)(nil),  // 8: vectorxlite_pb.CollectionExistsRequestPB
	(*CollectionExistsResponsePB)(nil), // 9: vectorxlite_pb.CollectionExistsResponsePB
	(*ExportSnapshotRequestPB)(nil),    // 10: vectorxlite_pb.ExportSnapshotRequestPB
	(*SnapshotChunkPB)(nil),            // 11: vectorxlite_pb.SnapshotChunkPB
	(*SnapshotMetadataPB)(nil),         // 12: vectorxlite_pb.SnapshotMetadataPB
	(*SnapshotFileInfoPB)(nil),         // 13: vectorxlite_pb.SnapshotFileInfoPB
	(*SnapshotFilePB)(nil),             // 14: vectorxlite_pb.SnapshotFilePB
	(*ImportSnapshotResponsePB)(nil),   // 15: vectorxlite_pb.ImportSnapshotResponsePB
}
var file_vectorxlite_v1_vectorxlite_proto_depIdxs = []int32{
	5,  // 0: vectorxlite_pb.SearchResultItemPB.payload:type_name -> vectorxlite_pb.KeyValuePB
	6,  // 1: vectorxlite_pb.SearchResponsePB.results:type_name -> vectorxlite_pb.SearchResultItemPB
	12, // 2: vectorxlite_pb.SnapshotChunkPB.metadata:type_name -> vectorxlite_pb.SnapshotMetadataPB
	14, // 3: vectorxlite_pb.SnapshotChunkPB.file_chunk:type_name -> vectorxlite_pb.SnapshotFilePB
	13, // 4: vectorxlite_pb.SnapshotMetadataPB.files:type_name -> vectorxlite_pb.SnapshotFileInfoPB
	0,  // 5: vectorxlite_pb.SnapshotFileInfoPB.file_type:type_name -> vectorxlite_pb.SnapshotFileTypePB
	2,  // 6: vectorxlite_pb.VectorXLitePB.CreateCollection:input_type -> vectorxlite_pb.CollectionConfigPB
	3,  // 7: vectorxlite_pb.VectorXLitePB.Insert:input_type -> vectorxlite_pb.InsertPointPB
	4,  // 8: vectorxlite_pb.VectorXLitePB.Search:input_type -> vectorxlite_pb.SearchPointPB
	8,  // 9: vectorxlite_pb.VectorXLitePB.CollectionExists:input_type -> vectorxlite_pb.CollectionExistsRequestPB
	10, // 10: vectorxlite_pb.VectorXLitePB.ExportSnapshot:input_type -> vectorxlite_pb.ExportSnapshotRequestPB
	11, // 11: vectorxlite_pb.VectorXLitePB.ImportSnapshot:input_type -> vectorxlite_pb.SnapshotChunkPB
	1,  // 12: vectorxlite_pb.VectorXLitePB.CreateCollection:output_type -> vectorxlite_pb.EmptyPB
	1,  // 13: vectorxlite_pb.VectorXLitePB.Insert:output_type -> vectorxlite_pb.EmptyPB
	7,  // 14: vectorxlite_pb.VectorXLitePB.Search:output_type -> vectorxlite_pb.SearchResponsePB
	9,  // 15: vectorxlite_pb.VectorXLitePB.CollectionExists:output_type -> vectorxlite_pb.CollectionExistsResponsePB
	11, // 16: vectorxlite_pb.VectorXLitePB.ExportSnapshot:output_type -> vectorxlite_pb.SnapshotChunkPB
	15, // 17: vectorxlite_pb.VectorXLitePB.ImportSnapshot:output_type -> vectorxlite_pb.ImportSnapshotResponsePB
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_vectorxlite_v1_vectorxlite_proto_init() }
func file_vectorxlite_v1_vectorxlite_proto_init() {
	if File_vectorxlite_v1_vectorxlite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vectorxlite_v1_vectorxlite_proto_rawDesc), len(file_vectorxlite_v1_vectorxlite_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vectorxlite_v1_vectorxlite_proto_goTypes,
		DependencyIndexes: file_vectorxlite_v1_vectorxlite_proto_depIdxs,
		EnumInfos:         file_vectorxlite_v1_vectorxlite_proto_enumTypes,
		MessageInfos:      file_vectorxlite_v1_vectorxlite_proto_msgTypes,
	}.Build()
	File_vectorxlite_v1_vectorxlite_proto = out.File
	file_vectorxlite_v1_vectorxlite_proto_goTypes = nil
	file_vectorxlite_v1_vectorxlite_proto_depIdxs = nil
}
