[package]
name = "vector_xlite"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlite-loadable = { version = "0.0.5", default-features = false }
rusqlite = { version = "0.37.0", features = ["load_extension" ]}
regex = "1.12.2"


