// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: vectorxlite.proto

package vectorxlite_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyPB) Reset() {
	*x = EmptyPB{}
	mi := &file_vectorxlite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyPB) ProtoMessage() {}

func (x *EmptyPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyPB.ProtoReflect.Descriptor instead.
func (*EmptyPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_proto_rawDescGZIP(), []int{0}
}

type CollectionConfigPB struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Distance           string                 `protobuf:"bytes,2,opt,name=distance,proto3" json:"distance,omitempty"` // e.g. "Cosine" | "Euclidean" | "Dot"
	VectorDimension    uint32                 `protobuf:"varint,3,opt,name=vector_dimension,json=vectorDimension,proto3" json:"vector_dimension,omitempty"`
	PayloadTableSchema string                 `protobuf:"bytes,4,opt,name=payload_table_schema,json=payloadTableSchema,proto3" json:"payload_table_schema,omitempty"`
	IndexFilePath      string                 `protobuf:"bytes,5,opt,name=index_file_path,json=indexFilePath,proto3" json:"index_file_path,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CollectionConfigPB) Reset() {
	*x = CollectionConfigPB{}
	mi := &file_vectorxlite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionConfigPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionConfigPB) ProtoMessage() {}

func (x *CollectionConfigPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionConfigPB.ProtoReflect.Descriptor instead.
func (*CollectionConfigPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_proto_rawDescGZIP(), []int{1}
}

func (x *CollectionConfigPB) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *CollectionConfigPB) GetDistance() string {
	if x != nil {
		return x.Distance
	}
	return ""
}

func (x *CollectionConfigPB) GetVectorDimension() uint32 {
	if x != nil {
		return x.VectorDimension
	}
	return 0
}

func (x *CollectionConfigPB) GetPayloadTableSchema() string {
	if x != nil {
		return x.PayloadTableSchema
	}
	return ""
}

func (x *CollectionConfigPB) GetIndexFilePath() string {
	if x != nil {
		return x.IndexFilePath
	}
	return ""
}

type InsertPointPB struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Id                 int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Vector             []float32              `protobuf:"fixed32,3,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	PayloadInsertQuery string                 `protobuf:"bytes,4,opt,name=payload_insert_query,json=payloadInsertQuery,proto3" json:"payload_insert_query,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InsertPointPB) Reset() {
	*x = InsertPointPB{}
	mi := &file_vectorxlite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertPointPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertPointPB) ProtoMessage() {}

func (x *InsertPointPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertPointPB.ProtoReflect.Descriptor instead.
func (*InsertPointPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_proto_rawDescGZIP(), []int{2}
}

func (x *InsertPointPB) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *InsertPointPB) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertPointPB) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *InsertPointPB) GetPayloadInsertQuery() string {
	if x != nil {
		return x.PayloadInsertQuery
	}
	return ""
}

type SearchPointPB struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CollectionName     string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Vector             []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK               uint32                 `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	PayloadSearchQuery string                 `protobuf:"bytes,4,opt,name=payload_search_query,json=payloadSearchQuery,proto3" json:"payload_search_query,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchPointPB) Reset() {
	*x = SearchPointPB{}
	mi := &file_vectorxlite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPointPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPointPB) ProtoMessage() {}

func (x *SearchPointPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPointPB.ProtoReflect.Descriptor instead.
func (*SearchPointPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_proto_rawDescGZIP(), []int{3}
}

func (x *SearchPointPB) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SearchPointPB) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchPointPB) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchPointPB) GetPayloadSearchQuery() string {
	if x != nil {
		return x.PayloadSearchQuery
	}
	return ""
}

type KeyValuePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValuePB) Reset() {
	*x = KeyValuePB{}
	mi := &file_vectorxlite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValuePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValuePB) ProtoMessage() {}

func (x *KeyValuePB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValuePB.ProtoReflect.Descriptor instead.
func (*KeyValuePB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_proto_rawDescGZIP(), []int{4}
}

func (x *KeyValuePB) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValuePB) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SearchResultItemPB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rowid         int64                  `protobuf:"varint,1,opt,name=rowid,proto3" json:"rowid,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Payload       []*KeyValuePB          `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResultItemPB) Reset() {
	*x = SearchResultItemPB{}
	mi := &file_vectorxlite_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResultItemPB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResultItemPB) ProtoMessage() {}

func (x *SearchResultItemPB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResultItemPB.ProtoReflect.Descriptor instead.
func (*SearchResultItemPB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResultItemPB) GetRowid() int64 {
	if x != nil {
		return x.Rowid
	}
	return 0
}

func (x *SearchResultItemPB) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SearchResultItemPB) GetPayload() []*KeyValuePB {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SearchResponsePB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResultItemPB  `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponsePB) Reset() {
	*x = SearchResponsePB{}
	mi := &file_vectorxlite_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponsePB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponsePB) ProtoMessage() {}

func (x *SearchResponsePB) ProtoReflect() protoreflect.Message {
	mi := &file_vectorxlite_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponsePB.ProtoReflect.Descriptor instead.
func (*SearchResponsePB) Descriptor() ([]byte, []int) {
	return file_vectorxlite_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponsePB) GetResults() []*SearchResultItemPB {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_vectorxlite_proto protoreflect.FileDescriptor

const file_vectorxlite_proto_rawDesc = "" +
	"\n" +
	"\x11vectorxlite.proto\x12\x0evectorxlite_pb\"\t\n" +
	"\aEmptyPB\"\xde\x01\n" +
	"\x12CollectionConfigPB\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\tR\bdistance\x12)\n" +
	"\x10vector_dimension\x18\x03 \x01(\rR\x0fvectorDimension\x120\n" +
	"\x14payload_table_schema\x18\x04 \x01(\tR\x12payloadTableSchema\x12&\n" +
	"\x0findex_file_path\x18\x05 \x01(\tR\rindexFilePath\"\x92\x01\n" +
	"\rInsertPointPB\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x16\n" +
	"\x06vector\x18\x03 \x03(\x02R\x06vector\x120\n" +
	"\x14payload_insert_query\x18\x04 \x01(\tR\x12payloadInsertQuery\"\x97\x01\n" +
	"\rSearchPointPB\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\rR\x04topK\x120\n" +
	"\x14payload_search_query\x18\x04 \x01(\tR\x12payloadSearchQuery\"4\n" +
	"\n" +
	"KeyValuePB\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"|\n" +
	"\x12SearchResultItemPB\x12\x14\n" +
	"\x05rowid\x18\x01 \x01(\x03R\x05rowid\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\x124\n" +
	"\apayload\x18\x03 \x03(\v2\x1a.vectorxlite_pb.KeyValuePBR\apayload\"P\n" +
	"\x10SearchResponsePB\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".vectorxlite_pb.SearchResultItemPBR\aresults2\xed\x01\n" +
	"\rVectorXLitePB\x12O\n" +
	"\x10CreateCollection\x12\".vectorxlite_pb.CollectionConfigPB\x1a\x17.vectorxlite_pb.EmptyPB\x12@\n" +
	"\x06Insert\x12\x1d.vectorxlite_pb.InsertPointPB\x1a\x17.vectorxlite_pb.EmptyPB\x12I\n" +
	"\x06Search\x12\x1d.vectorxlite_pb.SearchPointPB\x1a .vectorxlite_pb.SearchResponsePBBFZDgithub.com/uttom-akash/vector-xlite/go_grpc_client/pb;vectorxlite_pbb\x06proto3"

var (
	file_vectorxlite_proto_rawDescOnce sync.Once
	file_vectorxlite_proto_rawDescData []byte
)

func file_vectorxlite_proto_rawDescGZIP() []byte {
	file_vectorxlite_proto_rawDescOnce.Do(func() {
		file_vectorxlite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vectorxlite_proto_rawDesc), len(file_vectorxlite_proto_rawDesc)))
	})
	return file_vectorxlite_proto_rawDescData
}

var file_vectorxlite_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_vectorxlite_proto_goTypes = []any{
	(*EmptyPB)(nil),            // 0: vectorxlite_pb.EmptyPB
	(*CollectionConfigPB)(nil), // 1: vectorxlite_pb.CollectionConfigPB
	(*InsertPointPB)(nil),      // 2: vectorxlite_pb.InsertPointPB
	(*SearchPointPB)(nil),      // 3: vectorxlite_pb.SearchPointPB
	(*KeyValuePB)(nil),         // 4: vectorxlite_pb.KeyValuePB
	(*SearchResultItemPB)(nil), // 5: vectorxlite_pb.SearchResultItemPB
	(*SearchResponsePB)(nil),   // 6: vectorxlite_pb.SearchResponsePB
}
var file_vectorxlite_proto_depIdxs = []int32{
	4, // 0: vectorxlite_pb.SearchResultItemPB.payload:type_name -> vectorxlite_pb.KeyValuePB
	5, // 1: vectorxlite_pb.SearchResponsePB.results:type_name -> vectorxlite_pb.SearchResultItemPB
	1, // 2: vectorxlite_pb.VectorXLitePB.CreateCollection:input_type -> vectorxlite_pb.CollectionConfigPB
	2, // 3: vectorxlite_pb.VectorXLitePB.Insert:input_type -> vectorxlite_pb.InsertPointPB
	3, // 4: vectorxlite_pb.VectorXLitePB.Search:input_type -> vectorxlite_pb.SearchPointPB
	0, // 5: vectorxlite_pb.VectorXLitePB.CreateCollection:output_type -> vectorxlite_pb.EmptyPB
	0, // 6: vectorxlite_pb.VectorXLitePB.Insert:output_type -> vectorxlite_pb.EmptyPB
	6, // 7: vectorxlite_pb.VectorXLitePB.Search:output_type -> vectorxlite_pb.SearchResponsePB
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vectorxlite_proto_init() }
func file_vectorxlite_proto_init() {
	if File_vectorxlite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vectorxlite_proto_rawDesc), len(file_vectorxlite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vectorxlite_proto_goTypes,
		DependencyIndexes: file_vectorxlite_proto_depIdxs,
		MessageInfos:      file_vectorxlite_proto_msgTypes,
	}.Build()
	File_vectorxlite_proto = out.File
	file_vectorxlite_proto_goTypes = nil
	file_vectorxlite_proto_depIdxs = nil
}
